ayushma/utils/langchain.py, ayushma/views/chat.py
=> added system, human, ai message seprately

ayushma/serializers/project.py
=> Unset other projects as not default automatically

ayushma/views/chat.py
=> delete chat if first conversation fails

.pre-commit-config.yaml, ayushma/views/chat.py
=> fix: allow admin to access all chats

ayushma/serializers/users.py
Required for https://github.com/coronasafe/ayushma_fe/pull/17
=> Add password field to UserDetail serializer

ayushma/serializers/document.py, ayushma/utils/upload_file.py, ayushma/utils/upsert.py, core/settings/base.py
If the S3 credentials are not present or is invalid then the documents will be saved in the server inside the media folder.
=> Added fallback for S3 Upload

ayushma/serializers/users.py, ayushma/views/users.py
fixes issue #68 
Admin users can perform CRUD operations on user
=> Added CRUD operations for users

ayushma/utils/langchain.py, ayushma/utils/openaiapi.py, core/settings/base.py, requirements/base.txt
Updated the python dependencies in base.txt. Also, added the Azure OpenAI support to openaiapi.py and langchain.py by checking the OPENAI_API_TYPE environment variable. If it is 'azure', both classes will look for the respective Azure API-related environment variables, and then utilize the AzureOpenAI class from the langchain.llms module. Additionally, the 'openai_api_version' and the 'deployment_name' were added to the constructor of AzureOpenAI. This update will assist in utilizing the Azure OpenAI API and its functionalities.
=> Add embeddings endpoint support for Azure

ayushma/serializers/users.py
=> Fix registration endpoint

ayushma/views/users.py
=> fix: Profile not updating

ayushma/serializers/users.py, ayushma/views/users.py
- Added required fields to User Serializer
- Added search and field filters to Users
- Added `email` and `is_reviewer` to update user
=> Changes for User page

ayushma/utils/langchain.py, ayushma/utils/openaiapi.py, ayushma/utils/stream_callback.py
Frontend: https://github.com/coronasafe/ayushma_fe/pull/96
This PR adds functionality to catch any exception raised by LangChain/OpenAI and stream it through to the frontend to be displayed.
=> Catch and return errors while streaming

ayushma/utils/langchain.py, ayushma/utils/openaiapi.py
Required for: https://github.com/coronasafe/ayushma_fe/pull/97
=> Mark error message as SYSTEM

ayushma/views/chat.py, requirements/base.txt
Fixes: [Issue from FE #89](https://github.com/coronasafe/ayushma_fe/issues/89)
Ordering chats by descending order of created_at
Changed botocore version to 1.31.34
=> Changed chats list order to descending

utils/helpers.py
Fixes a crash on user registration.
=> Fix Registration endpoint crash

ayushma/serializers/chat.py, ayushma/utils/converse.py, ayushma/views/chat.py
Frontend: https://github.com/coronasafe/ayushma_fe/pull/102
=> Refactor chat feedback to use external_id

ayushma/views/project.py
Related PR for https://github.com/coronasafe/ayushma_fe/issues/87
=> Added a filter to retrieve archived projects

ayushma/views/project.py
Fixes #336 
Add an endpoint to delete a project
=> Add an endpoint to delete project

ayushma/utils/speech_to_text.py
This pull request removes the sample rate from the code.
=> Remove sample rate

ayushma/utils/speech_to_text.py
This pull request adds the functionality to convert speech to text using the provided audio. It includes a new function `speech_to_text` in the `speech_to_text.py` file that utilizes the specified speech recognition engine.
=> Fix speech recognition functionality

.github/workflows/test-base.yaml, .github/workflows/test.yaml, Makefile, compose/local/django/Dockerfile
- Resolves #460 
- Adds workflow to test build the docker image
- Checks for missing migrations
=> Adds workflow to test build docker image

ayushma/utils/speech_to_text.py
=> OpenAI STT fixed

ayushma/models/chat.py, ayushma/serializers/chat.py, ayushma/utils/converse.py, ayushma/views/chat.py
=> immediate display transcribed text added

ayushma/models/enums.py, ayushma/utils/converse.py, ayushma/utils/openaiapi.py, ayushma/views/orphan.py
This PR introduces new API routes to Ayushma, aimed at supporting the Care Scribe feature by enabling voice-to-text transcription and AI-powered completion for form filling. These additions are crucial for the seamless integration between Ayushma and the Care platform, facilitating a more accessible and efficient user experience.
- Ayushma: https://github.com/coronasafe/ayushma/pull/493
- Care Backend: https://github.com/coronasafe/care/pull/2020
- Care Frontend: https://github.com/coronasafe/care_fe/pull/7481
- **Speech to Text Support**: Enhanced the `enums.py` and `views/orphan.py` to include support for speech-to-text transcription, utilizing different engines based on project needs. This allows for dynamic transcription of voice inputs into text, serving as the foundational step for …
=> Add Support for Care Scribe Transcription and AI Completion Routes

.devcontainer/Dockerfile, .github/workflows/linter.yaml, .pre-commit-config.yaml, .vscode/settings.json, Makefile, ayushma/admin.py, ayushma/apps.py, ayushma/management/commands/upsert.py, ayushma/models/services.py, ayushma/models/token.py, ayushma/permissions.py, ayushma/serializers/document.py, ayushma/serializers/testsuite.py, ayushma/token.py, ayushma/utils/converse.py, ayushma/views/auth.py, ayushma/views/chat.py, ayushma/views/orphan.py, ayushma/views/service.py, ayushma/views/token.py, core/settings/local.py, pyproject.toml, setup.cfg
=> fix: Adds Linter CI and maintains formatting across codebase

ayushma/views/chat.py
Filter the ChatFeedback using the chat's external id and return that in a new route: `/feedbacks`
=> Show chat's feedbacks
